export const membersData = [
  {
    name: "Ayush Singh",
    post: "President",
    img: "/members/Ayush.jpg",
    linkedin: "https://www.linkedin.com/in/aayush-singh-6b5978253",
    github: "https://github.com/DevilHeartlesss",
  },
  {
    name: "Shreehita Thati",
    post: "Marketing Lead",
    img: "/members/Shree.jpg",
    linkedin: "https://www.linkedin.com/in/sreehithathati03",
    github: "https://github.com/sreehithathati03",
  },
  {
    name: "Sooraj",
    post: "Web Development Lead",
    img: "/members/Sooraj.jpg",
    linkedin: "https://www.linkedin.com/in/sooraj-bhaskar-nambiar",
    github: "https://github.com/Sooraj002",
  },
  {
    name: "Krish Khanna",
    post: "Management Lead",
    img: "/members/Krish.jpg",
    linkedin: "https://www.linkedin.com/in/krish-k-498774234",
    github: "https://github.com/krishkh",
  },
  {
    name: "Manisha Kumari",
    post: "UI/UX Designer",
    img: "/members/Manisha.jpg",
    linkedin: "https://www.linkedin.com/in/manishakumari21",
    github: "https://github.com/Manishakumari21",
  },
  {
    name: "Adista Nautiyal",
    post: "Web Dev member",
    img: "/members/Adista.jpg",
    linkedin: "https://www.linkedin.com/in/adista-nautiyal-3011a7294",
    github: "https://github.com/adistanautiyal",
  },
  {
    name: "Shivang Shukla",
    post: "DSA Member",
    img: "/members/Shivang.jpg",
    linkedin: "https://www.linkedin.com/in/shivang-shukla-6212012b2/",
    github: "https://github.com/Shivang1611",
  },
  {
    name: "Shivangi Bhartiya",
    post: "DSA member",
    img: "/members/Shivangi.jpg",
    linkedin: "https://www.linkedin.com/in/shivangi-bhartiya-39336b294/",
    github: "https://github.com/ShivangiBhartiya",
  },
  {
    name: "Anurag raj",
    post: "DSA Member",
    img: "/members/Anurag.jpg",
    linkedin: "https://www.linkedin.com/in/anurag-raj-821214216/",
    github: "https://github.com/Anurag07-07",
  },
  {
    name: "Rianna Bansal",
    post: "DSA Member",
    img: "/members/Rianna.jpg",
    linkedin: "https://www.linkedin.com/in/rianna-bansal-a4972031a/",
    github: "https://github.com/Rianna17",
  },
];
