export const membersData = [
  {
    name: "Shreehita Thati",
    post: "Founder",
    img: "/members/Shree.jpg",
    linkedin: "https://www.linkedin.com/in/sreehithathati03",
    github: "https://github.com/sreehithathati03",
  },
  {
    name: "Krish Khanna",
    post: "Founder",
    img: "/members/Krish.jpg",
    linkedin: "https://www.linkedin.com/in/krish-k-498774234",
    github: "https://github.com/krishkh",
  },
  {
    name: "Sooraj",
    post: "Member",
    img: "/members/Sooraj.jpg",
    linkedin: "https://www.linkedin.com/in/sooraj-bhaskar-nambiar",
    github: "https://github.com/Sooraj002",
  },
  {
    name: "Ayush Singh",
    post: "Member",
    img: "/members/Ayush.jpg",
    linkedin: "https://www.linkedin.com/in/aayush-singh-6b5978253",
    github: "https://github.com/DevilHeartlesss",
  },
  {
    name: "Manisha Kumari",
    post: "Member",
    img: "/members/Manisha.jpg",
    linkedin: "https://www.linkedin.com/in/manishakumari21",
    github: "https://github.com/Manishakumari21",
  },
  {
    name: "Adista Nautiyal",
    post: "Member",
    img: "/members/Adista.jpg",
    linkedin: "https://www.linkedin.com/in/adista-nautiyal-3011a7294",
    github: "https://github.com/adistanautiyal",
  },
  {
    name: "Shivansh Saxena",
    post: "Member",
    img: "/members/Shivansh.jpg",
    linkedin: "https://www.linkedin.com/in/shivansh-saxena-58215a29b",
    github: "https://github.com/shivansh4565",
  },
  {
    name: "Shivang Shukla",
    post: "Member",
    img: "/members/Shivang.jpg",
    linkedin: "https://www.linkedin.com/in/shivang-shukla-6212012b2/",
  },
  {
    name: "Shivangi Bhartiya",
    post: "Member",
    img: "/members/Shivangi.jpg",
    linkedin: "https://www.linkedin.com/in/shivangi-bhartiya-39336b294/",
    github: "https://github.com/ShivangiBhartiya",
  },
  {
    name: "Anurag raj",
    post: "Member",
    img: "/members/Anurag.jpg",
    linkedin: "https://www.linkedin.com/in/anurag-raj-821214216/",
    github: "https://github.com/Anurag07-07",
  },
  {
    name: "Rianna Bansal",
    post: "Member",
    img: "/members/Rianna.jpg",
    linkedin: "https://www.linkedin.com/in/rianna-bansal-a4972031a/",
    github: "https://github.com/Rianna17",
  },
];
